### ISSUE TITLE
Enums should follow Swift conventions

### ISSUE THREAD

**Issue by minuscorp** [hallelujahbaby/CFDraggableMessage#2]
This enumerations should be changed from:
```swift
public enum Theme {
        case Success(Style)
        case Fail(Style)
        case Info(Style)
        case Warning(Style)
    }

    public enum Style {
        case Light
        case Dark
    }
```
To:
```swift
public enum Theme {
        case success(Style)
        case fail(Style)
        case info(Style)
        case warning(Style)
    }

    public enum Style {
        case light
        case dark
    }
```
In order to follow the Swift enumeration conventions as accepted in [here](https://github.com/apple/swift-evolution/blob/master/proposals/0006-apply-api-guidelines-to-the-standard-library.md)

**Comment by JT501** [comment]
Thank you for reminding 😄 . I have fixed it in [1.0.1 Release](https://github.com/hallelujahbaby/CFNotify/releases/tag/1.0.1).
