### ISSUE TITLE
iTunes Store submission issue

### ISSUE THREAD

**Issue by andreyz** [hallelujahbaby/CFDraggableMessage#3]
Getting this back from Apple:
```Invalid Bundle Structure - The binary file '<Appname>.app/Frameworks/CFNotify.framework/CFResources.bundle/CFResources' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide for information on the iOS app bundle structure.```

**Comment by andreyz** [comment]
I am including this project manually. To solve the issue I needed to remove `CFResources.bundle` from `CFNotify`'s _Copy Bundle Resources_ step in CFNotify.xcodeproj for CFNotify target.

Probably a good thing to do as well for anyone else using the project.

**Comment by andreyz** [comment]
Update: the workaround described above, allowed me to submit the app, but resources from CFResources.bundle aren't visible in notifications from CFNotify.

**Comment by JT501** [comment]
Sorry for late reply, I'm just back from a trip. I will have a look on it in this few days.

**Comment by JT501** [comment]
I found out that an unnecessary **executable** was generated in **CFResources.bundle**. After plenty of trials, the generation of the executable seems cannot be avoided. Thus, I do it in violent way, I added a Run Script in Build phase to remove the executable everytime the framework is built.

I have tested uploading to App Store, the error is gone and all good. Please try the latest version of the framework. If the problem still exist, please re-open this issue. Thank you.
